 int mainw = 800;
  int mainh = 600;
  int maintoph = 140;
  int mainmidh = 10;
  int lil = 13;
  int lilboxsp =  20;
  int oc20 = 20;
  int oc40 = 40;
  int oc60 = 60;
  int oc80 = 80;
  int cw = 40;
  int ch = 175;
 void setup() { 
   size(mainw, mainh); 
   background(255); 
   noStroke();

   color sdblue1 = color(7, 38, 99);
   color sdblue2 = color(2, 105, 214);
   color sdblue3 = color(133, 172, 221);
   color sdblue4 = color(11, 111, 255);
   color sdblue5 = color (151, 198, 255);
   color sdblue6 = color (0, 177, 255); 
   colorMode(RGB, 255, 255, 255); 
 
 // main body
   fill(sdblue1); 
     rect ( 0, maintoph, mainw, maintoph); 
        fill(sdblue2); 
     rect ( 0, maintoph * 2, mainw, mainmidh); 
   fill(sdblue1); 
     rect ( 0, maintoph * 2 + mainmidh , mainw, maintoph); 
 
      fill(sdblue3); 
     rect ( 0, maintoph, lil, lil); 
      fill(sdblue4); 
     rect ( lilboxsp , maintoph, lil, lil); 
      fill(sdblue6 , oc20); 
     rect ( lilboxsp * 2 , maintoph, lil, lil); 
     fill(sdblue5); 
     rect ( lilboxsp * 3 , maintoph, lil, lil); 
     fill(sdblue4); 
     rect ( lilboxsp * 4 , maintoph, lil, lil); 
      fill(sdblue6 , oc60); 
     rect ( lilboxsp * 5 , maintoph, lil, lil); 
     fill(sdblue3); 
     rect ( lilboxsp * 6 , maintoph, lil, lil); 
     fill(sdblue5); 
     rect ( lilboxsp * 7 , maintoph, lil, lil); 
     fill(sdblue4); 
     rect ( lilboxsp * 8 , maintoph, lil, lil); 
      fill(sdblue6 , oc60); 
     rect ( lilboxsp * 9 , maintoph, lil, lil); 
     fill(sdblue3); 
     rect ( lilboxsp * 10 , maintoph, lil, lil); 
      fill(sdblue3); 
      rect ( lilboxsp * 11, maintoph, lil, lil); 
      fill(sdblue6); 
     rect ( lilboxsp * 12 , maintoph, lil, lil); 
     fill(sdblue5); 
     rect ( lilboxsp * 13 , maintoph, lil, lil); 
     fill(sdblue4 , oc80); 
     rect ( lilboxsp * 14 , maintoph, lil, lil); 
      fill(sdblue6); 
     rect ( lilboxsp * 15 , maintoph, lil, lil); 
     fill(sdblue3); 
     rect ( lilboxsp * 16 , maintoph, lil, lil); 
     fill(sdblue5); 
     rect ( lilboxsp * 17 , maintoph, lil, lil); 
     fill(sdblue4 , oc40); 
     rect ( lilboxsp * 18 , maintoph, lil, lil); 
      fill(sdblue6); 
     rect ( lilboxsp * 19 , maintoph, lil, lil); 
     fill(sdblue3); 
     rect ( lilboxsp * 20 , maintoph, lil, lil); 
     fill(sdblue3); 
      rect ( lilboxsp * 11, maintoph, lil, lil); 
      fill(sdblue6); 
     rect ( lilboxsp * 12 , maintoph, lil, lil); 
     fill(sdblue5); 
     rect ( lilboxsp * 13 , maintoph, lil, lil); 
     fill(sdblue4); 
     rect ( lilboxsp * 14 , maintoph, lil, lil); 
      fill(sdblue6, oc80); 
     rect ( lilboxsp * 15 , maintoph, lil, lil); 
     fill(sdblue3); 
     rect ( lilboxsp * 16 , maintoph, lil, lil); 
     fill(sdblue5); 
     rect ( lilboxsp * 17 , maintoph, lil, lil); 
     fill(sdblue4); 
     rect ( lilboxsp * 18 , maintoph, lil, lil); 
      fill(sdblue6); 
     rect ( lilboxsp * 19 , maintoph, lil, lil); 
     fill(sdblue3); 
     rect ( lilboxsp * 20 , maintoph, lil, lil); 
     
           fill(sdblue3); 
      rect ( lilboxsp * 21, maintoph, lil, lil); 
      fill(sdblue6); 
     rect ( lilboxsp * 22 , maintoph, lil, lil); 
     fill(sdblue5, oc60); 
     rect ( lilboxsp * 23 , maintoph, lil, lil); 
     fill(sdblue4); 
     rect ( lilboxsp * 24 , maintoph, lil, lil); 
      fill(sdblue6 ); 
     rect ( lilboxsp * 25 , maintoph, lil, lil); 
     fill(sdblue3); 
     rect ( lilboxsp * 26 , maintoph, lil, lil); 
     fill(sdblue5, oc20); 
     rect ( lilboxsp * 27 , maintoph, lil, lil); 
     fill(sdblue4); 
     rect ( lilboxsp * 28 , maintoph, lil, lil); 
      fill(sdblue6); 
     rect ( lilboxsp * 29 , maintoph, lil, lil); 
     fill(sdblue3); 
     rect ( lilboxsp * 30 , maintoph, lil, lil); 
     
       fill(sdblue3); 
      rect ( lilboxsp * 31, maintoph, lil, lil); 
      fill(sdblue6); 
     rect ( lilboxsp * 32 , maintoph, lil, lil); 
     fill(sdblue5); 
     rect ( lilboxsp * 33 , maintoph, lil, lil); 
     fill(sdblue4 , oc40); 
     rect ( lilboxsp * 34 , maintoph, lil, lil); 
      fill(sdblue6); 
     rect ( lilboxsp * 35 , maintoph, lil, lil); 
     fill(sdblue3); 
     rect ( lilboxsp * 36 , maintoph, lil, lil); 
     fill(sdblue5); 
     rect ( lilboxsp * 37 , maintoph, lil, lil); 
     fill(sdblue4); 
     rect ( lilboxsp * 38 , maintoph, lil, lil); 
      fill(sdblue6); 
     rect ( lilboxsp * 39 , maintoph, lil, lil); 
     fill(sdblue3, oc20); 
     rect ( lilboxsp * 40 , maintoph, lil, lil); 
     
       fill(sdblue3); 
      rect ( lilboxsp * 41, maintoph, lil, lil); 
      fill(sdblue6); 
     rect ( lilboxsp * 42 , maintoph, lil, lil); 
     fill(sdblue5); 
     rect ( lilboxsp * 43 , maintoph, lil, lil); 
     fill(sdblue4); 
     rect ( lilboxsp * 44 , maintoph, lil, lil); 
      fill(sdblue6); 
     rect ( lilboxsp * 45 , maintoph, lil, lil); 
     fill(sdblue3); 
     rect ( lilboxsp * 46 , maintoph, lil, lil); 
     fill(sdblue5); 
     rect ( lilboxsp * 47 , maintoph, lil, lil); 
     fill(sdblue4); 
     rect ( lilboxsp * 48 , maintoph, lil, lil); 
      fill(sdblue6); 
     rect ( lilboxsp * 49 , maintoph, lil, lil); 
     fill(sdblue3); 
     rect ( lilboxsp * 50 , maintoph, lil, lil);  
     fill(sdblue3); 
      rect ( lilboxsp * 51, maintoph, lil, lil); 
      fill(sdblue6); 
     rect ( lilboxsp * 52 , maintoph, lil, lil); 
     fill(sdblue5); 
     rect ( lilboxsp * 53 , maintoph, lil, lil); 
     fill(sdblue4); 
     rect ( lilboxsp * 54 , maintoph, lil, lil); 
      fill(sdblue6); 
     rect ( lilboxsp * 55 , maintoph, lil, lil);  
 
 // fristline

     fill(sdblue3); 
     rect ( 0, maintoph + lilboxsp , lil, lil); 
      fill(sdblue5); 
     rect ( lilboxsp , maintoph  + lilboxsp, lil, lil); 
      fill(sdblue4); 
     rect ( lilboxsp * 2 , maintoph  + lilboxsp, lil, lil); 
     fill(sdblue6); 
     rect ( lilboxsp * 3 , maintoph + lilboxsp, lil, lil); 
     fill(sdblue5 , oc60); 
     rect ( lilboxsp * 4 , maintoph + lilboxsp, lil, lil); 
      fill(sdblue4); 
     rect ( lilboxsp * 5 , maintoph + lilboxsp, lil, lil); 
     fill(sdblue6); 
     rect ( lilboxsp * 6 , maintoph + lilboxsp, lil, lil); 
     fill(sdblue5); 
     rect ( lilboxsp * 7 , maintoph + lilboxsp, lil, lil); 
     fill(sdblue3); 
     rect ( lilboxsp * 8 , maintoph + lilboxsp, lil, lil); 
      fill(sdblue5); 
     rect ( lilboxsp * 9 , maintoph + lilboxsp, lil, lil); 
     fill(sdblue6); 
     rect ( lilboxsp * 10 , maintoph + lilboxsp, lil, lil); 
      fill(sdblue3); 
      rect ( lilboxsp * 11, maintoph + lilboxsp, lil, lil); 
      fill(sdblue6, oc80); 
     rect ( lilboxsp * 12 , maintoph + lilboxsp, lil, lil); 
     fill(sdblue4); 
     rect ( lilboxsp * 13 , maintoph + lilboxsp, lil, lil); 
     fill(sdblue3); 
     rect ( lilboxsp * 14 , maintoph + lilboxsp, lil, lil); 
      fill(sdblue4); 
     rect ( lilboxsp * 15 , maintoph + lilboxsp, lil, lil); 
     fill(sdblue5); 
     rect ( lilboxsp * 16 , maintoph + lilboxsp, lil, lil); 
     fill(sdblue6); 
     rect ( lilboxsp * 17 , maintoph + lilboxsp, lil, lil); 
     fill(sdblue5); 
     rect ( lilboxsp * 18 , maintoph + lilboxsp, lil, lil); 
      fill(sdblue4, oc60); 
     rect ( lilboxsp * 19 , maintoph + lilboxsp , lil, lil); 
     fill(sdblue6); 
     rect ( lilboxsp * 20 , maintoph + lilboxsp, lil, lil); 
     fill(sdblue4); 
    
           fill(sdblue5); 
      rect ( lilboxsp * 21, maintoph + lilboxsp, lil, lil); 
      fill(sdblue3); 
     rect ( lilboxsp * 22 , maintoph + lilboxsp, lil, lil); 
     fill(sdblue4); 
     rect ( lilboxsp * 23 , maintoph + lilboxsp, lil, lil); 
     fill(sdblue5); 
     rect ( lilboxsp * 24 , maintoph + lilboxsp, lil, lil); 
      fill(sdblue4); 
     rect ( lilboxsp * 25 , maintoph + lilboxsp, lil, lil); 
     fill(sdblue6, oc20); 
     rect ( lilboxsp * 26 , maintoph + lilboxsp, lil, lil); 
     fill(sdblue4); 
     rect ( lilboxsp * 27 , maintoph + lilboxsp, lil, lil); 
     fill(sdblue3); 
     rect ( lilboxsp * 28 , maintoph + lilboxsp, lil, lil); 
      fill(sdblue5); 
     rect ( lilboxsp * 29 , maintoph + lilboxsp, lil, lil); 
     fill(sdblue3); 
     rect ( lilboxsp * 30 , maintoph + lilboxsp, lil, lil); 
     
       fill(sdblue5); 
      rect ( lilboxsp * 31, maintoph + lilboxsp, lil, lil); 
      fill(sdblue4); 
     rect ( lilboxsp * 32 , maintoph + lilboxsp, lil, lil); 
     fill(sdblue3); 
     rect ( lilboxsp * 33 , maintoph + lilboxsp, lil, lil); 
     fill(sdblue5); 
     rect ( lilboxsp * 34 , maintoph + lilboxsp, lil, lil); 
      fill(sdblue4); 
     rect ( lilboxsp * 35 , maintoph + lilboxsp, lil, lil); 
     fill(sdblue3); 
     rect ( lilboxsp * 36 , maintoph + lilboxsp, lil, lil); 
     fill(sdblue6); 
     rect ( lilboxsp * 37 , maintoph + lilboxsp, lil, lil); 
     fill(sdblue5, oc60); 
     rect ( lilboxsp * 38 , maintoph + lilboxsp, lil, lil); 
      fill(sdblue4); 
     rect ( lilboxsp * 39 , maintoph + lilboxsp, lil, lil); 
     fill(sdblue3); 
     rect ( lilboxsp * 40 , maintoph + lilboxsp, lil, lil); 
     
       fill(sdblue4); 
      rect ( lilboxsp * 41, maintoph + lilboxsp, lil, lil); 
      fill(sdblue3); 
     rect ( lilboxsp * 42 , maintoph + lilboxsp, lil, lil); 
     fill(sdblue6, oc40); 
     rect ( lilboxsp * 43 , maintoph + lilboxsp, lil, lil); 
     fill(sdblue6); 
     rect ( lilboxsp * 44 , maintoph + lilboxsp, lil, lil); 
      fill(sdblue3); 
     rect ( lilboxsp * 45 , maintoph + lilboxsp, lil, lil); 
     fill(sdblue5); 
     rect ( lilboxsp * 46 , maintoph + lilboxsp, lil, lil); 
     fill(sdblue6); 
     rect ( lilboxsp * 47 , maintoph + lilboxsp, lil, lil); 
     fill(sdblue3); 
     rect ( lilboxsp * 48 , maintoph + lilboxsp, lil, lil); 
      fill(sdblue4); 
     rect ( lilboxsp * 49 , maintoph + lilboxsp, lil, lil); 
     fill(sdblue6); 
     rect ( lilboxsp * 50 , maintoph + lilboxsp, lil, lil);  
     fill(sdblue3, oc20); 
      rect ( lilboxsp * 51, maintoph + lilboxsp, lil, lil); 
      fill(sdblue5); 
     rect ( lilboxsp * 52 , maintoph + lilboxsp, lil, lil); 
     fill(sdblue4); 
     rect ( lilboxsp * 53 , maintoph + lilboxsp, lil, lil); 
     fill(sdblue5, oc60); 
     rect ( lilboxsp * 54 , maintoph + lilboxsp, lil, lil); 
      fill(sdblue3); 
     rect ( lilboxsp * 55 , maintoph + lilboxsp, lil, lil);  
//  second line 

     fill(sdblue4, oc20); 
     rect ( 0, maintoph + lilboxsp * 2 , lil, lil); 
      fill(sdblue5); 
     rect ( lilboxsp , maintoph  + lilboxsp * 2, lil, lil); 
      fill(sdblue4); 
     rect ( lilboxsp * 2 , maintoph  + lilboxsp * 2, lil, lil); 
     fill(sdblue6); 
     rect ( lilboxsp * 3 , maintoph + lilboxsp * 2, lil, lil); 
     fill(sdblue5);  
     rect ( lilboxsp * 4 , maintoph + lilboxsp * 2, lil, lil); 
      fill(sdblue4); 
     rect ( lilboxsp * 5 , maintoph + lilboxsp * 2, lil, lil); 
     fill(sdblue6); 
     rect ( lilboxsp * 6 , maintoph + lilboxsp * 2, lil, lil); 
     fill(sdblue5); 
     rect ( lilboxsp * 7 , maintoph + lilboxsp * 2, lil, lil); 
     fill(sdblue3, oc60); 
     rect ( lilboxsp * 8 , maintoph + lilboxsp * 2, lil, lil); 
      fill(sdblue5); 
     rect ( lilboxsp * 9 , maintoph + lilboxsp * 2, lil, lil); 
     fill(sdblue6); 
     rect ( lilboxsp * 10 , maintoph + lilboxsp * 2, lil, lil); 
      fill(sdblue3); 
      rect ( lilboxsp * 11, maintoph + lilboxsp * 2, lil, lil); 
      fill(sdblue6); 
     rect ( lilboxsp * 12 , maintoph + lilboxsp * 2, lil, lil); 
     fill(sdblue4, oc80); 
     rect ( lilboxsp * 13 , maintoph + lilboxsp * 2, lil, lil); 
     fill(sdblue3); 
     rect ( lilboxsp * 14 , maintoph + lilboxsp * 2, lil, lil); 
      fill(sdblue4); 
     rect ( lilboxsp * 15 , maintoph + lilboxsp * 2, lil, lil); 
     fill(sdblue5); 
     rect ( lilboxsp * 16 , maintoph + lilboxsp * 2, lil, lil); 
     fill(sdblue6); 
     rect ( lilboxsp * 17 , maintoph + lilboxsp * 2, lil, lil); 
     fill(sdblue5); 
     rect ( lilboxsp * 18 , maintoph + lilboxsp * 2, lil, lil); 
      fill(sdblue4); 
     rect ( lilboxsp * 19 , maintoph + lilboxsp * 2 , lil, lil); 
     fill(sdblue6, oc80); 
     rect ( lilboxsp * 20 , maintoph + lilboxsp * 2, lil, lil); 
     fill(sdblue4); 
    
           fill(sdblue5); 
      rect ( lilboxsp * 21, maintoph + lilboxsp * 2, lil, lil); 
      fill(sdblue3); 
     rect ( lilboxsp * 22 , maintoph + lilboxsp * 2, lil, lil); 
     fill(sdblue4); 
     rect ( lilboxsp * 23 , maintoph + lilboxsp * 2, lil, lil); 
     fill(sdblue5); 
     rect ( lilboxsp * 24 , maintoph + lilboxsp * 2, lil, lil); 
      fill(sdblue4); 
     rect ( lilboxsp * 25 , maintoph + lilboxsp * 2, lil, lil); 
     fill(sdblue6); 
     rect ( lilboxsp * 26 , maintoph + lilboxsp * 2, lil, lil); 
     fill(sdblue4); 
     rect ( lilboxsp * 27 , maintoph + lilboxsp * 2, lil, lil); 
     fill(sdblue3); 
     rect ( lilboxsp * 28 , maintoph + lilboxsp * 2, lil, lil); 
      fill(sdblue5, oc80); 
     rect ( lilboxsp * 29 , maintoph + lilboxsp * 2, lil, lil); 
     fill(sdblue3); 
     rect ( lilboxsp * 30 , maintoph + lilboxsp * 2, lil, lil); 
     
       fill(sdblue5, oc60); 
      rect ( lilboxsp * 31, maintoph + lilboxsp * 2, lil, lil); 
      fill(sdblue4); 
     rect ( lilboxsp * 32 , maintoph + lilboxsp * 2, lil, lil); 
     fill(sdblue3); 
     rect ( lilboxsp * 33 , maintoph + lilboxsp * 2, lil, lil); 
     fill(sdblue5); 
     rect ( lilboxsp * 34 , maintoph + lilboxsp * 2, lil, lil); 
      fill(sdblue4); 
     rect ( lilboxsp * 35 , maintoph + lilboxsp * 2, lil, lil); 
     fill(sdblue3); 
     rect ( lilboxsp * 36 , maintoph + lilboxsp * 2, lil, lil); 
     fill(sdblue6); 
     rect ( lilboxsp * 37 , maintoph + lilboxsp * 2, lil, lil); 
     fill(sdblue5, oc40); 
     rect ( lilboxsp * 38 , maintoph + lilboxsp * 2, lil, lil); 
      fill(sdblue4); 
     rect ( lilboxsp * 39 , maintoph + lilboxsp * 2, lil, lil); 
     fill(sdblue3, oc80); 
     rect ( lilboxsp * 40 , maintoph + lilboxsp * 2, lil, lil); 
     
       fill(sdblue4, oc20); 
      rect ( lilboxsp * 41, maintoph + lilboxsp * 2, lil, lil); 
      fill(sdblue3); 
     rect ( lilboxsp * 42 , maintoph + lilboxsp * 2, lil, lil); 
     fill(sdblue6); 
     rect ( lilboxsp * 43 , maintoph + lilboxsp * 2, lil, lil); 
     fill(sdblue6); 
     rect ( lilboxsp * 44 , maintoph + lilboxsp * 2, lil, lil); 
      fill(sdblue3); 
     rect ( lilboxsp * 45 , maintoph + lilboxsp * 2, lil, lil); 
     fill(sdblue5, oc60); 
     rect ( lilboxsp * 46 , maintoph + lilboxsp * 2, lil, lil); 
     fill(sdblue6); 
     rect ( lilboxsp * 47 , maintoph + lilboxsp * 2, lil, lil); 
     fill(sdblue3); 
     rect ( lilboxsp * 48 , maintoph + lilboxsp * 2, lil, lil); 
      fill(sdblue4); 
     rect ( lilboxsp * 49 , maintoph + lilboxsp * 2, lil, lil); 
     fill(sdblue6); 
     rect ( lilboxsp * 50 , maintoph + lilboxsp * 2, lil, lil);  
     fill(sdblue3); 
      rect ( lilboxsp * 51, maintoph + lilboxsp * 2, lil, lil); 
      fill(sdblue5); 
     rect ( lilboxsp * 52 , maintoph + lilboxsp * 2, lil, lil); 
     fill(sdblue4); 
     rect ( lilboxsp * 53 , maintoph + lilboxsp * 2, lil, lil); 
     fill(sdblue5); 
     rect ( lilboxsp * 54 , maintoph + lilboxsp * 2, lil, lil); 
      fill(sdblue3); 
     rect ( lilboxsp * 55 , maintoph + lilboxsp * 2, lil, lil);  
// 3rd loine 
     fill(sdblue3); 
     rect ( 0, maintoph + lilboxsp * 3 , lil, lil); 
      fill(sdblue5, oc60); 
     rect ( lilboxsp , maintoph  + lilboxsp * 3, lil, lil); 
      fill(sdblue4); 
     rect ( lilboxsp * 2 , maintoph  + lilboxsp * 3, lil, lil); 
     fill(sdblue6); 
     rect ( lilboxsp * 3 , maintoph + lilboxsp * 3, lil, lil); 
     fill(sdblue5); 
     rect ( lilboxsp * 4 , maintoph + lilboxsp * 3, lil, lil); 
      fill(sdblue4, oc60); 
     rect ( lilboxsp * 5 , maintoph + lilboxsp * 3, lil, lil); 
     fill(sdblue6); 
     rect ( lilboxsp * 6 , maintoph + lilboxsp * 3, lil, lil); 
     fill(sdblue5); 
     rect ( lilboxsp * 7 , maintoph + lilboxsp * 3, lil, lil); 
     fill(sdblue3); 
     rect ( lilboxsp * 8 , maintoph + lilboxsp * 3, lil, lil); 
      fill(sdblue5); 
     rect ( lilboxsp * 9 , maintoph + lilboxsp * 3, lil, lil); 
     fill(sdblue6); 
     rect ( lilboxsp * 10 , maintoph + lilboxsp * 3, lil, lil); 
      fill(sdblue3); 
      rect ( lilboxsp * 11, maintoph + lilboxsp * 3, lil, lil); 
      fill(sdblue6, oc20); 
     rect ( lilboxsp * 12 , maintoph + lilboxsp * 3, lil, lil); 
     fill(sdblue4); 
     rect ( lilboxsp * 13 , maintoph + lilboxsp * 3, lil, lil); 
     fill(sdblue3); 
     rect ( lilboxsp * 14 , maintoph + lilboxsp * 3, lil, lil); 
      fill(sdblue4); 
     rect ( lilboxsp * 15 , maintoph + lilboxsp * 3, lil, lil); 
     fill(sdblue5); 
     rect ( lilboxsp * 16 , maintoph + lilboxsp * 3, lil, lil); 
     fill(sdblue6, oc40); 
     rect ( lilboxsp * 17 , maintoph + lilboxsp * 3, lil, lil); 
     fill(sdblue5); 
     rect ( lilboxsp * 18 , maintoph + lilboxsp * 3, lil, lil); 
      fill(sdblue4); 
     rect ( lilboxsp * 19 , maintoph + lilboxsp * 3 , lil, lil); 
     fill(sdblue6); 
     rect ( lilboxsp * 20 , maintoph + lilboxsp * 3, lil, lil); 
     fill(sdblue4); 
    
           fill(sdblue5, oc80); 
      rect ( lilboxsp * 21, maintoph + lilboxsp * 3, lil, lil); 
      fill(sdblue3); 
     rect ( lilboxsp * 22 , maintoph + lilboxsp * 3, lil, lil); 
     fill(sdblue4); 
     rect ( lilboxsp * 23 , maintoph + lilboxsp * 3, lil, lil); 
     fill(sdblue5); 
     rect ( lilboxsp * 24 , maintoph + lilboxsp * 3, lil, lil); 
      fill(sdblue4); 
     rect ( lilboxsp * 25 , maintoph + lilboxsp * 3, lil, lil); 
     fill(sdblue6 , oc60); 
     rect ( lilboxsp * 26 , maintoph + lilboxsp * 3, lil, lil); 
     fill(sdblue4); 
     rect ( lilboxsp * 27 , maintoph + lilboxsp * 3, lil, lil); 
     fill(sdblue3); 
     rect ( lilboxsp * 28 , maintoph + lilboxsp * 3, lil, lil); 
      fill(sdblue5); 
     rect ( lilboxsp * 29 , maintoph + lilboxsp * 3, lil, lil); 
     fill(sdblue3); 
     rect ( lilboxsp * 30 , maintoph + lilboxsp * 3, lil, lil); 
     
       fill(sdblue5); 
      rect ( lilboxsp * 31, maintoph + lilboxsp * 3, lil, lil); 
      fill(sdblue4, oc20); 
     rect ( lilboxsp * 32 , maintoph + lilboxsp * 3, lil, lil); 
     fill(sdblue3); 
     rect ( lilboxsp * 33 , maintoph + lilboxsp * 3, lil, lil); 
     fill(sdblue5); 
     rect ( lilboxsp * 34 , maintoph + lilboxsp * 3, lil, lil); 
      fill(sdblue4); 
     rect ( lilboxsp * 35 , maintoph + lilboxsp * 3, lil, lil); 
     fill(sdblue3); 
     rect ( lilboxsp * 36 , maintoph + lilboxsp * 3, lil, lil); 
     fill(sdblue6); 
     rect ( lilboxsp * 37 , maintoph + lilboxsp * 3, lil, lil); 
     fill(sdblue5, oc60); 
     rect ( lilboxsp * 38 , maintoph + lilboxsp * 3, lil, lil); 
      fill(sdblue4); 
     rect ( lilboxsp * 39 , maintoph + lilboxsp * 3, lil, lil); 
     fill(sdblue3); 
     rect ( lilboxsp * 40 , maintoph + lilboxsp * 3, lil, lil); 
     
       fill(sdblue4); 
      rect ( lilboxsp * 41, maintoph + lilboxsp * 3, lil, lil); 
      fill(sdblue3); 
     rect ( lilboxsp * 42 , maintoph + lilboxsp * 3, lil, lil); 
     fill(sdblue6, oc20); 
     rect ( lilboxsp * 43 , maintoph + lilboxsp * 3, lil, lil); 
     fill(sdblue6); 
     rect ( lilboxsp * 44 , maintoph + lilboxsp * 3, lil, lil); 
      fill(sdblue3); 
     rect ( lilboxsp * 45 , maintoph + lilboxsp * 3, lil, lil); 
     fill(sdblue5); 
     rect ( lilboxsp * 46 , maintoph + lilboxsp * 3, lil, lil); 
     fill(sdblue6); 
     rect ( lilboxsp * 47 , maintoph + lilboxsp * 3, lil, lil); 
     fill(sdblue3); 
     rect ( lilboxsp * 48 , maintoph + lilboxsp * 3, lil, lil); 
      fill(sdblue4); 
     rect ( lilboxsp * 49 , maintoph + lilboxsp * 3, lil, lil); 
     fill(sdblue6); 
     rect ( lilboxsp * 50 , maintoph + lilboxsp * 3, lil, lil);  
     fill(sdblue3); 
      rect ( lilboxsp * 51, maintoph + lilboxsp * 3, lil, lil); 
      fill(sdblue5); 
     rect ( lilboxsp * 52 , maintoph + lilboxsp * 3, lil, lil); 
     fill(sdblue4); 
     rect ( lilboxsp * 53 , maintoph + lilboxsp * 3, lil, lil); 
     fill(sdblue5); 
     rect ( lilboxsp * 54 , maintoph + lilboxsp * 3, lil, lil); 
      fill(sdblue3); 
     rect ( lilboxsp * 55 , maintoph + lilboxsp * 3, lil, lil);
//4th line
     fill(sdblue3); 
     rect ( 0, maintoph + lilboxsp * 4 , lil, lil); 
      fill(sdblue5); 
     rect ( lilboxsp , maintoph  + lilboxsp * 4, lil, lil); 
      fill(sdblue4); 
     rect ( lilboxsp * 2 , maintoph  + lilboxsp * 4, lil, lil); 
     fill(sdblue6); 
     rect ( lilboxsp * 3 , maintoph + lilboxsp * 4, lil, lil); 
     fill(sdblue5, oc20); 
     rect ( lilboxsp * 4 , maintoph + lilboxsp * 4, lil, lil); 
      fill(sdblue4); 
     rect ( lilboxsp * 5 , maintoph + lilboxsp * 4, lil, lil); 
     fill(sdblue6); 
     rect ( lilboxsp * 6 , maintoph + lilboxsp * 4, lil, lil); 
     fill(sdblue5); 
     rect ( lilboxsp * 7 , maintoph + lilboxsp * 4, lil, lil); 
     fill(sdblue3); 
     rect ( lilboxsp * 8 , maintoph + lilboxsp * 4, lil, lil); 
      fill(sdblue5); 
     rect ( lilboxsp * 9 , maintoph + lilboxsp * 4, lil, lil); 
     fill(sdblue6); 
     rect ( lilboxsp * 10 , maintoph + lilboxsp * 4, lil, lil); 
      fill(sdblue3, oc60); 
      rect ( lilboxsp * 11, maintoph + lilboxsp * 4, lil, lil); 
      fill(sdblue6); 
     rect ( lilboxsp * 12 , maintoph + lilboxsp * 4, lil, lil); 
     fill(sdblue4); 
     rect ( lilboxsp * 13 , maintoph + lilboxsp * 4, lil, lil); 
     fill(sdblue3); 
     rect ( lilboxsp * 14 , maintoph + lilboxsp * 4, lil, lil); 
      fill(sdblue4); 
     rect ( lilboxsp * 15 , maintoph + lilboxsp * 4, lil, lil); 
     fill(sdblue5); 
     rect ( lilboxsp * 16 , maintoph + lilboxsp * 4, lil, lil); 
     fill(sdblue6, oc80); 
     rect ( lilboxsp * 17 , maintoph + lilboxsp * 4, lil, lil); 
     fill(sdblue5); 
     rect ( lilboxsp * 18 , maintoph + lilboxsp * 4, lil, lil); 
      fill(sdblue4); 
     rect ( lilboxsp * 19 , maintoph + lilboxsp * 4 , lil, lil); 
     fill(sdblue6); 
     rect ( lilboxsp * 20 , maintoph + lilboxsp * 4, lil, lil); 
     fill(sdblue4); 
    
           fill(sdblue5); 
      rect ( lilboxsp * 21, maintoph + lilboxsp * 4, lil, lil); 
      fill(sdblue3); 
     rect ( lilboxsp * 22 , maintoph + lilboxsp * 4, lil, lil); 
     fill(sdblue4, oc20); 
     rect ( lilboxsp * 23 , maintoph + lilboxsp * 4, lil, lil); 
     fill(sdblue5); 
     rect ( lilboxsp * 24 , maintoph + lilboxsp * 4, lil, lil); 
      fill(sdblue4); 
     rect ( lilboxsp * 25 , maintoph + lilboxsp * 4, lil, lil); 
     fill(sdblue6); 
     rect ( lilboxsp * 26 , maintoph + lilboxsp * 4, lil, lil); 
     fill(sdblue4, oc60); 
     rect ( lilboxsp * 27 , maintoph + lilboxsp * 4, lil, lil); 
     fill(sdblue3); 
     rect ( lilboxsp * 28 , maintoph + lilboxsp * 4, lil, lil); 
      fill(sdblue5); 
     rect ( lilboxsp * 29 , maintoph + lilboxsp * 4, lil, lil); 
     fill(sdblue3); 
     rect ( lilboxsp * 30 , maintoph + lilboxsp * 4, lil, lil); 
     
       fill(sdblue5); 
      rect ( lilboxsp * 31, maintoph + lilboxsp * 4, lil, lil); 
      fill(sdblue4, oc60); 
     rect ( lilboxsp * 32 , maintoph + lilboxsp * 4, lil, lil); 
     fill(sdblue3); 
     rect ( lilboxsp * 33 , maintoph + lilboxsp * 4, lil, lil); 
     fill(sdblue5); 
     rect ( lilboxsp * 34 , maintoph + lilboxsp * 4, lil, lil); 
      fill(sdblue4, oc80); 
     rect ( lilboxsp * 35 , maintoph + lilboxsp * 4, lil, lil); 
     fill(sdblue3); 
     rect ( lilboxsp * 36 , maintoph + lilboxsp * 4, lil, lil); 
     fill(sdblue6); 
     rect ( lilboxsp * 37 , maintoph + lilboxsp * 4, lil, lil); 
     fill(sdblue5); 
     rect ( lilboxsp * 38 , maintoph + lilboxsp * 4, lil, lil); 
      fill(sdblue4); 
     rect ( lilboxsp * 39 , maintoph + lilboxsp * 4, lil, lil); 
     fill(sdblue3); 
     rect ( lilboxsp * 40 , maintoph + lilboxsp * 4, lil, lil); 
     
       fill(sdblue4); 
      rect ( lilboxsp * 41, maintoph + lilboxsp * 4, lil, lil); 
      fill(sdblue3, oc60); 
     rect ( lilboxsp * 42 , maintoph + lilboxsp * 4, lil, lil); 
     fill(sdblue6); 
     rect ( lilboxsp * 43 , maintoph + lilboxsp * 4, lil, lil); 
     fill(sdblue6); 
     rect ( lilboxsp * 44 , maintoph + lilboxsp * 4, lil, lil); 
      fill(sdblue3); 
     rect ( lilboxsp * 45 , maintoph + lilboxsp * 4, lil, lil); 
     fill(sdblue5); 
     rect ( lilboxsp * 46 , maintoph + lilboxsp * 4, lil, lil); 
     fill(sdblue6); 
     rect ( lilboxsp * 47 , maintoph + lilboxsp * 4, lil, lil); 
     fill(sdblue3); 
     rect ( lilboxsp * 48 , maintoph + lilboxsp * 4, lil, lil); 
      fill(sdblue4, oc20); 
     rect ( lilboxsp * 49 , maintoph + lilboxsp * 4, lil, lil); 
     fill(sdblue6); 
     rect ( lilboxsp * 50 , maintoph + lilboxsp * 4, lil, lil);  
     fill(sdblue3); 
      rect ( lilboxsp * 51, maintoph + lilboxsp * 4, lil, lil); 
      fill(sdblue5, oc20); 
     rect ( lilboxsp * 52 , maintoph + lilboxsp * 4, lil, lil); 
     fill(sdblue4); 
     rect ( lilboxsp * 53 , maintoph + lilboxsp * 4, lil, lil); 
     fill(sdblue5); 
     rect ( lilboxsp * 54 , maintoph + lilboxsp * 4, lil, lil); 
      fill(sdblue3); 
     rect ( lilboxsp * 55 , maintoph + lilboxsp * 4, lil, lil);
//5thline

     fill(sdblue3, oc80); 
     rect ( 0, maintoph + lilboxsp * 5 , lil, lil); 
      fill(sdblue5); 
     rect ( lilboxsp , maintoph  + lilboxsp * 5, lil, lil); 
      fill(sdblue4); 
     rect ( lilboxsp * 2 , maintoph  + lilboxsp * 5, lil, lil); 
     fill(sdblue6); 
     rect ( lilboxsp * 3 , maintoph + lilboxsp * 5, lil, lil); 
     fill(sdblue5); 
     rect ( lilboxsp * 4 , maintoph + lilboxsp * 5, lil, lil); 
      fill(sdblue4, oc40); 
     rect ( lilboxsp * 5 , maintoph + lilboxsp * 5, lil, lil); 
     fill(sdblue6); 
     rect ( lilboxsp * 6 , maintoph + lilboxsp * 5, lil, lil); 
     fill(sdblue5); 
     rect ( lilboxsp * 7 , maintoph + lilboxsp * 5, lil, lil); 
     fill(sdblue3); 
     rect ( lilboxsp * 8 , maintoph + lilboxsp * 5, lil, lil); 
      fill(sdblue5); 
     rect ( lilboxsp * 9 , maintoph + lilboxsp *5, lil, lil); 
     fill(sdblue6, oc60); 
     rect ( lilboxsp * 10 , maintoph + lilboxsp * 5, lil, lil); 
      fill(sdblue3); 
      rect ( lilboxsp * 11, maintoph + lilboxsp * 5, lil, lil); 
      fill(sdblue6); 
     rect ( lilboxsp * 12 , maintoph + lilboxsp * 5, lil, lil); 
     fill(sdblue4); 
     rect ( lilboxsp * 13 , maintoph + lilboxsp * 5, lil, lil); 
     fill(sdblue3); 
     rect ( lilboxsp * 14 , maintoph + lilboxsp * 5, lil, lil); 
      fill(sdblue4); 
     rect ( lilboxsp * 15 , maintoph + lilboxsp * 5, lil, lil); 
     fill(sdblue5, oc60); 
     rect ( lilboxsp * 16 , maintoph + lilboxsp * 5, lil, lil); 
     fill(sdblue6); 
     rect ( lilboxsp * 17 , maintoph + lilboxsp * 5, lil, lil); 
     fill(sdblue5); 
     rect ( lilboxsp * 18 , maintoph + lilboxsp * 5, lil, lil); 
      fill(sdblue4); 
     rect ( lilboxsp * 19 , maintoph + lilboxsp * 5 , lil, lil); 
     fill(sdblue6); 
     rect ( lilboxsp * 20 , maintoph + lilboxsp * 5, lil, lil); 
     fill(sdblue4); 
    
           fill(sdblue5, oc80); 
      rect ( lilboxsp * 21, maintoph + lilboxsp * 5, lil, lil); 
      fill(sdblue3); 
     rect ( lilboxsp * 22 , maintoph + lilboxsp * 5, lil, lil); 
     fill(sdblue4); 
     rect ( lilboxsp * 23 , maintoph + lilboxsp * 5, lil, lil); 
     fill(sdblue5, oc80); 
     rect ( lilboxsp * 24 , maintoph + lilboxsp * 5, lil, lil); 
      fill(sdblue4); 
     rect ( lilboxsp * 25 , maintoph + lilboxsp * 5, lil, lil); 
     fill(sdblue6, oc80); 
     rect ( lilboxsp * 26 , maintoph + lilboxsp * 5, lil, lil); 
     fill(sdblue4); 
     rect ( lilboxsp * 27 , maintoph + lilboxsp * 5, lil, lil); 
     fill(sdblue3); 
     rect ( lilboxsp * 28 , maintoph + lilboxsp * 5, lil, lil); 
      fill(sdblue5); 
     rect ( lilboxsp * 29 , maintoph + lilboxsp * 5, lil, lil); 
     fill(sdblue3); 
     rect ( lilboxsp * 30 , maintoph + lilboxsp * 5, lil, lil); 
     
       fill(sdblue5); 
      rect ( lilboxsp * 31, maintoph + lilboxsp * 5, lil, lil); 
      fill(sdblue4, oc60); 
     rect ( lilboxsp * 32 , maintoph + lilboxsp * 5, lil, lil); 
     fill(sdblue3); 
     rect ( lilboxsp * 33 , maintoph + lilboxsp * 5, lil, lil); 
     fill(sdblue5); 
     rect ( lilboxsp * 34 , maintoph + lilboxsp * 5, lil, lil); 
      fill(sdblue4); 
     rect ( lilboxsp * 35 , maintoph + lilboxsp * 5, lil, lil); 
     fill(sdblue3); 
     rect ( lilboxsp * 36 , maintoph + lilboxsp * 5, lil, lil); 
     fill(sdblue6); 
     rect ( lilboxsp * 37 , maintoph + lilboxsp * 5, lil, lil); 
     fill(sdblue5); 
     rect ( lilboxsp * 38 , maintoph + lilboxsp * 5, lil, lil); 
      fill(sdblue4, oc20); 
     rect ( lilboxsp * 39 , maintoph + lilboxsp * 5, lil, lil); 
     fill(sdblue3); 
     rect ( lilboxsp * 40 , maintoph + lilboxsp * 5, lil, lil); 
     
       fill(sdblue4, oc40); 
      rect ( lilboxsp * 41, maintoph + lilboxsp * 5, lil, lil); 
      fill(sdblue3); 
     rect ( lilboxsp * 42 , maintoph + lilboxsp * 5, lil, lil); 
     fill(sdblue6); 
     rect ( lilboxsp * 43 , maintoph + lilboxsp * 5, lil, lil); 
     fill(sdblue6); 
     rect ( lilboxsp * 44 , maintoph + lilboxsp * 5, lil, lil); 
      fill(sdblue3); 
     rect ( lilboxsp * 45 , maintoph + lilboxsp * 5, lil, lil); 
     fill(sdblue5); 
     rect ( lilboxsp * 46 , maintoph + lilboxsp * 5, lil, lil); 
     fill(sdblue6); 
     rect ( lilboxsp * 47 , maintoph + lilboxsp * 5, lil, lil); 
     fill(sdblue3); 
     rect ( lilboxsp * 48 , maintoph + lilboxsp * 5, lil, lil); 
      fill(sdblue4); 
     rect ( lilboxsp * 49 , maintoph + lilboxsp * 5, lil, lil); 
     fill(sdblue6); 
     rect ( lilboxsp * 50 , maintoph + lilboxsp * 5, lil, lil);  
     fill(sdblue3, oc20); 
      rect ( lilboxsp * 51, maintoph + lilboxsp * 5, lil, lil); 
      fill(sdblue5); 
     rect ( lilboxsp * 52 , maintoph + lilboxsp * 5, lil, lil); 
     fill(sdblue4); 
     rect ( lilboxsp * 53 , maintoph + lilboxsp * 5, lil, lil); 
     fill(sdblue5); 
     rect ( lilboxsp * 54 , maintoph + lilboxsp * 5, lil, lil); 
      fill(sdblue3); 
     rect ( lilboxsp * 55 , maintoph + lilboxsp * 5, lil, lil);
//6thline
     fill(sdblue3); 
     rect ( 0, maintoph + lilboxsp * 6 , lil, lil); 
      fill(sdblue5); 
     rect ( lilboxsp , maintoph  + lilboxsp * 6, lil, lil); 
      fill(sdblue4, oc20); 
     rect ( lilboxsp * 2 , maintoph  + lilboxsp * 6, lil, lil); 
     fill(sdblue6); 
     rect ( lilboxsp * 3 , maintoph + lilboxsp * 6, lil, lil); 
     fill(sdblue5); 
     rect ( lilboxsp * 4 , maintoph + lilboxsp * 6, lil, lil); 
      fill(sdblue4); 
     rect ( lilboxsp * 5 , maintoph + lilboxsp * 6, lil, lil); 
     fill(sdblue6); 
     rect ( lilboxsp * 6 , maintoph + lilboxsp * 6, lil, lil); 
     fill(sdblue5); 
     rect ( lilboxsp * 7 , maintoph + lilboxsp * 6, lil, lil); 
     fill(sdblue3, oc40); 
     rect ( lilboxsp * 8 , maintoph + lilboxsp * 6, lil, lil); 
      fill(sdblue5); 
     rect ( lilboxsp * 9 , maintoph + lilboxsp * 6, lil, lil); 
     fill(sdblue6); 
     rect ( lilboxsp * 10 , maintoph + lilboxsp * 6, lil, lil); 
      fill(sdblue3); 
      rect ( lilboxsp * 11, maintoph + lilboxsp * 6, lil, lil); 
      fill(sdblue6); 
     rect ( lilboxsp * 12 , maintoph + lilboxsp * 6, lil, lil); 
     fill(sdblue4); 
     rect ( lilboxsp * 13 , maintoph + lilboxsp * 6, lil, lil); 
     fill(sdblue3); 
     rect ( lilboxsp * 14 , maintoph + lilboxsp * 6, lil, lil); 
      fill(sdblue4, oc80); 
     rect ( lilboxsp * 15 , maintoph + lilboxsp * 6, lil, lil); 
     fill(sdblue5); 
     rect ( lilboxsp * 16 , maintoph + lilboxsp * 6, lil, lil); 
     fill(sdblue6); 
     rect ( lilboxsp * 17 , maintoph + lilboxsp * 6, lil, lil); 
     fill(sdblue5); 
     rect ( lilboxsp * 18 , maintoph + lilboxsp * 6, lil, lil); 
      fill(sdblue4, oc20); 
     rect ( lilboxsp * 19 , maintoph + lilboxsp * 6 , lil, lil); 
     fill(sdblue6); 
     rect ( lilboxsp * 20 , maintoph + lilboxsp * 6, lil, lil); 
     fill(sdblue4); 
    
           fill(sdblue5, oc60); 
      rect ( lilboxsp * 21, maintoph + lilboxsp * 6, lil, lil); 
      fill(sdblue3); 
     rect ( lilboxsp * 22 , maintoph + lilboxsp * 6, lil, lil); 
     fill(sdblue4); 
     rect ( lilboxsp * 23 , maintoph + lilboxsp * 6, lil, lil); 
     fill(sdblue5); 
     rect ( lilboxsp * 24 , maintoph + lilboxsp * 6, lil, lil); 
      fill(sdblue4); 
     rect ( lilboxsp * 25 , maintoph + lilboxsp * 6, lil, lil); 
     fill(sdblue6); 
     rect ( lilboxsp * 26 , maintoph + lilboxsp * 6, lil, lil); 
     fill(sdblue4); 
     rect ( lilboxsp * 27 , maintoph + lilboxsp * 6, lil, lil); 
     fill(sdblue3); 
     rect ( lilboxsp * 28 , maintoph + lilboxsp * 6, lil, lil); 
      fill(sdblue5, oc20); 
     rect ( lilboxsp * 29 , maintoph + lilboxsp * 6, lil, lil); 
     fill(sdblue3); 
     rect ( lilboxsp * 30 , maintoph + lilboxsp * 6, lil, lil); 
     
       fill(sdblue5); 
      rect ( lilboxsp * 31, maintoph + lilboxsp * 6, lil, lil); 
      fill(sdblue4); 
     rect ( lilboxsp * 32 , maintoph + lilboxsp * 6, lil, lil); 
     fill(sdblue3 , oc20); 
     rect ( lilboxsp * 33 , maintoph + lilboxsp * 6, lil, lil); 
     fill(sdblue5); 
     rect ( lilboxsp * 34 , maintoph + lilboxsp * 6, lil, lil); 
      fill(sdblue4); 
     rect ( lilboxsp * 35 , maintoph + lilboxsp * 6, lil, lil); 
     fill(sdblue3, oc60); 
     rect ( lilboxsp * 36 , maintoph + lilboxsp * 6, lil, lil); 
     fill(sdblue6); 
     rect ( lilboxsp * 37 , maintoph + lilboxsp * 6, lil, lil); 
     fill(sdblue5); 
     rect ( lilboxsp * 38 , maintoph + lilboxsp * 6, lil, lil); 
      fill(sdblue4); 
     rect ( lilboxsp * 39 , maintoph + lilboxsp * 6, lil, lil); 
     fill(sdblue3); 
     rect ( lilboxsp * 40 , maintoph + lilboxsp * 6, lil, lil); 
     
       fill(sdblue4); 
      rect ( lilboxsp * 41, maintoph + lilboxsp * 6, lil, lil); 
      fill(sdblue3, oc20); 
     rect ( lilboxsp * 42 , maintoph + lilboxsp * 6, lil, lil); 
     fill(sdblue6); 
     rect ( lilboxsp * 43 , maintoph + lilboxsp * 6, lil, lil); 
     fill(sdblue6); 
     rect ( lilboxsp * 44 , maintoph + lilboxsp * 6, lil, lil); 
      fill(sdblue3); 
     rect ( lilboxsp * 45 , maintoph + lilboxsp * 6, lil, lil); 
     fill(sdblue5); 
     rect ( lilboxsp * 46 , maintoph + lilboxsp * 6, lil, lil); 
     fill(sdblue6); 
     rect ( lilboxsp * 47 , maintoph + lilboxsp * 6, lil, lil); 
     fill(sdblue3); 
     rect ( lilboxsp * 48 , maintoph + lilboxsp * 6, lil, lil); 
      fill(sdblue4); 
     rect ( lilboxsp * 49 , maintoph + lilboxsp * 6, lil, lil); 
     fill(sdblue6); 
     rect ( lilboxsp * 50 , maintoph + lilboxsp * 6, lil, lil);  
     fill(sdblue3); 
      rect ( lilboxsp * 51, maintoph + lilboxsp * 6, lil, lil); 
      fill(sdblue5); 
     rect ( lilboxsp * 52 , maintoph + lilboxsp * 6, lil, lil); 
     fill(sdblue4); 
     rect ( lilboxsp * 53 , maintoph + lilboxsp * 6, lil, lil); 
     fill(sdblue5); 
     rect ( lilboxsp * 54 , maintoph + lilboxsp * 6, lil, lil); 
      fill(sdblue3); 
     rect ( lilboxsp * 55 , maintoph + lilboxsp * 6, lil, lil);
//8thline
     fill(sdblue3); 
     rect ( 0, maintoph + lilboxsp * 8 , lil, lil); 
      fill(sdblue4, oc20); 
     rect ( lilboxsp , maintoph  + lilboxsp * 8, lil, lil); 
      fill(sdblue4); 
     rect ( lilboxsp * 2 , maintoph  + lilboxsp * 8, lil, lil); 
     fill(sdblue6 ); 
     rect ( lilboxsp * 3 , maintoph + lilboxsp * 8, lil, lil); 
     fill(sdblue5); 
     rect ( lilboxsp * 4 , maintoph + lilboxsp * 8, lil, lil); 
      fill(sdblue4); 
     rect ( lilboxsp * 5 , maintoph + lilboxsp * 8, lil, lil); 
     fill(sdblue6, oc80); 
     rect ( lilboxsp * 6 , maintoph + lilboxsp * 8, lil, lil); 
     fill(sdblue5); 
     rect ( lilboxsp * 7 , maintoph + lilboxsp * 8, lil, lil); 
     fill(sdblue3); 
     rect ( lilboxsp * 8 , maintoph + lilboxsp * 8, lil, lil); 
      fill(sdblue5, oc40); 
     rect ( lilboxsp * 9 , maintoph + lilboxsp * 8, lil, lil); 
     fill(sdblue6); 
     rect ( lilboxsp * 10 , maintoph + lilboxsp * 8, lil, lil); 
      fill(sdblue3); 
      rect ( lilboxsp * 11, maintoph + lilboxsp * 8, lil, lil); 
      fill(sdblue6); 
     rect ( lilboxsp * 12 , maintoph + lilboxsp * 8, lil, lil); 
     fill(sdblue4, oc60); 
     rect ( lilboxsp * 13 , maintoph + lilboxsp * 8, lil, lil); 
     fill(sdblue3); 
     rect ( lilboxsp * 14 , maintoph + lilboxsp * 8, lil, lil); 
      fill(sdblue4); 
     rect ( lilboxsp * 15 , maintoph + lilboxsp * 8, lil, lil); 
     fill(sdblue5, oc40); 
     rect ( lilboxsp * 16 , maintoph + lilboxsp * 8, lil, lil); 
     fill(sdblue6); 
     rect ( lilboxsp * 17 , maintoph + lilboxsp * 8, lil, lil); 
     fill(sdblue5); 
     rect ( lilboxsp * 18 , maintoph + lilboxsp * 8, lil, lil); 
      fill(sdblue4); 
     rect ( lilboxsp * 19 , maintoph + lilboxsp * 8 , lil, lil); 
     fill(sdblue6); 
     rect ( lilboxsp * 20 , maintoph + lilboxsp * 8, lil, lil); 
     fill(sdblue4, oc80); 
    
           fill(sdblue5); 
      rect ( lilboxsp * 21, maintoph + lilboxsp * 8, lil, lil); 
      fill(sdblue3, oc60); 
     rect ( lilboxsp * 22 , maintoph + lilboxsp * 8, lil, lil); 
     fill(sdblue4); 
     rect ( lilboxsp * 23 , maintoph + lilboxsp * 8, lil, lil); 
     fill(sdblue5); 
     rect ( lilboxsp * 24 , maintoph + lilboxsp * 8, lil, lil); 
      fill(sdblue4); 
     rect ( lilboxsp * 25 , maintoph + lilboxsp * 8, lil, lil); 
     fill(sdblue6); 
     rect ( lilboxsp * 26 , maintoph + lilboxsp * 8, lil, lil); 
     fill(sdblue4); 
     rect ( lilboxsp * 27 , maintoph + lilboxsp * 8, lil, lil); 
     fill(sdblue3, oc80); 
     rect ( lilboxsp * 28 , maintoph + lilboxsp * 8, lil, lil); 
      fill(sdblue5); 
     rect ( lilboxsp * 29 , maintoph + lilboxsp * 8, lil, lil); 
     fill(sdblue3); 
     rect ( lilboxsp * 30 , maintoph + lilboxsp * 8, lil, lil); 
     
       fill(sdblue5); 
      rect ( lilboxsp * 31, maintoph + lilboxsp * 8, lil, lil); 
      fill(sdblue4, oc60); 
     rect ( lilboxsp * 32 , maintoph + lilboxsp * 8, lil, lil); 
     fill(sdblue3); 
     rect ( lilboxsp * 33 , maintoph + lilboxsp * 8, lil, lil); 
     fill(sdblue5); 
     rect ( lilboxsp * 34 , maintoph + lilboxsp * 8, lil, lil); 
      fill(sdblue4); 
     rect ( lilboxsp * 35 , maintoph + lilboxsp * 8, lil, lil); 
     fill(sdblue3); 
     rect ( lilboxsp * 36 , maintoph + lilboxsp * 8, lil, lil); 
     fill(sdblue6 , oc80); 
     rect ( lilboxsp * 37 , maintoph + lilboxsp * 8, lil, lil); 
     fill(sdblue5); 
     rect ( lilboxsp * 38 , maintoph + lilboxsp * 8, lil, lil); 
      fill(sdblue4); 
     rect ( lilboxsp * 39 , maintoph + lilboxsp * 8, lil, lil); 
     fill(sdblue3); 
     rect ( lilboxsp* 40 , maintoph + lilboxsp * 8, lil, lil); 
     
       fill(sdblue4, oc40); 
      rect ( lilboxsp * 41, maintoph + lilboxsp * 8, lil, lil); 
      fill(sdblue3); 
     rect ( lilboxsp * 42 , maintoph + lilboxsp * 8, lil, lil); 
     fill(sdblue6); 
     rect ( lilboxsp * 43 , maintoph + lilboxsp * 8, lil, lil); 
     fill(sdblue6); 
     rect ( lilboxsp * 44 , maintoph + lilboxsp * 8, lil, lil); 
      fill(sdblue3); 
     rect ( lilboxsp * 45 , maintoph + lilboxsp * 8, lil, lil); 
     fill(sdblue5); 
     rect ( lilboxsp * 46 , maintoph + lilboxsp * 8, lil, lil); 
     fill(sdblue6); 
     rect ( lilboxsp * 47 , maintoph + lilboxsp * 8, lil, lil); 
     fill(sdblue3); 
     rect ( lilboxsp * 48 , maintoph + lilboxsp * 8, lil, lil); 
      fill(sdblue4); 
     rect ( lilboxsp * 49 , maintoph + lilboxsp * 8, lil, lil); 
     fill(sdblue6, oc20); 
     rect ( lilboxsp * 50 , maintoph + lilboxsp * 8, lil, lil);  
     fill(sdblue3); 
      rect ( lilboxsp * 51, maintoph + lilboxsp * 8, lil, lil); 
      fill(sdblue5); 
     rect ( lilboxsp * 52 , maintoph + lilboxsp * 8, lil, lil); 
     fill(sdblue4, oc80); 
     rect ( lilboxsp * 53 , maintoph + lilboxsp * 8, lil, lil); 
     fill(sdblue5); 
     rect ( lilboxsp * 54 , maintoph + lilboxsp * 8, lil, lil); 

//9thline
     fill(sdblue3, oc40 ); 
     rect ( 0, maintoph + lilboxsp * 9 , lil, lil); 
      fill(sdblue5); 
     rect ( lilboxsp , maintoph  + lilboxsp * 9, lil, lil); 
      fill(sdblue4); 
     rect ( lilboxsp * 2 , maintoph  + lilboxsp * 9, lil, lil); 
     fill(sdblue6); 
     rect ( lilboxsp * 3 , maintoph + lilboxsp * 9, lil, lil); 
     fill(sdblue5); 
     rect ( lilboxsp * 4 , maintoph + lilboxsp * 9, lil, lil); 
      fill(sdblue4); 
     rect ( lilboxsp * 5 , maintoph + lilboxsp * 9, lil, lil); 
     fill(sdblue6); 
     rect ( lilboxsp * 6 , maintoph + lilboxsp * 9, lil, lil); 
     fill(sdblue5); 
     rect ( lilboxsp * 7 , maintoph + lilboxsp * 9, lil, lil); 
     fill(sdblue3); 
     rect ( lilboxsp * 8 , maintoph + lilboxsp * 9, lil, lil); 
      fill(sdblue5); 
     rect ( lilboxsp * 9 , maintoph + lilboxsp * 9, lil, lil); 
     fill(sdblue6); 
     rect ( lilboxsp * 10 , maintoph + lilboxsp * 9, lil, lil); 
      fill(sdblue3); 
      rect ( lilboxsp * 11, maintoph + lilboxsp * 9, lil, lil); 
      fill(sdblue6); 
     rect ( lilboxsp * 12 , maintoph + lilboxsp * 9, lil, lil); 
     fill(sdblue4); 
     rect ( lilboxsp * 13 , maintoph + lilboxsp * 9, lil, lil); 
     fill(sdblue3); 
     rect ( lilboxsp * 14 , maintoph + lilboxsp * 9, lil, lil); 
      fill(sdblue4); 
     rect ( lilboxsp * 15 , maintoph + lilboxsp * 9, lil, lil); 
     fill(sdblue5); 
     rect ( lilboxsp * 16 , maintoph + lilboxsp * 9, lil, lil); 
     fill(sdblue6); 
     rect ( lilboxsp * 17 , maintoph + lilboxsp * 9, lil, lil); 
     fill(sdblue5); 
     rect ( lilboxsp * 18 , maintoph + lilboxsp * 9, lil, lil); 
      fill(sdblue4); 
     rect ( lilboxsp * 19 , maintoph + lilboxsp * 9 , lil, lil); 
     fill(sdblue6); 
     rect ( lilboxsp * 20 , maintoph + lilboxsp * 9, lil, lil); 
     fill(sdblue4); 
    
           fill(sdblue5); 
      rect ( lilboxsp * 21, maintoph + lilboxsp * 9, lil, lil); 
      fill(sdblue3); 
     rect ( lilboxsp * 22 , maintoph + lilboxsp * 9, lil, lil); 
     fill(sdblue4); 
     rect ( lilboxsp * 23 , maintoph + lilboxsp * 9, lil, lil); 
     fill(sdblue5); 
     rect ( lilboxsp * 24 , maintoph + lilboxsp * 9, lil, lil); 
      fill(sdblue4); 
     rect ( lilboxsp * 25 , maintoph + lilboxsp * 9, lil, lil); 
     fill(sdblue6); 
     rect ( lilboxsp * 26 , maintoph + lilboxsp * 9, lil, lil); 
     fill(sdblue4); 
     rect ( lilboxsp * 27 , maintoph + lilboxsp * 9, lil, lil); 
     fill(sdblue3); 
     rect ( lilboxsp * 28 , maintoph + lilboxsp * 9, lil, lil); 
      fill(sdblue5); 
     rect ( lilboxsp * 29 , maintoph + lilboxsp * 9, lil, lil); 
     fill(sdblue3); 
     rect ( lilboxsp * 30 , maintoph + lilboxsp * 9, lil, lil); 
     
       fill(sdblue5); 
      rect ( lilboxsp * 31, maintoph + lilboxsp * 9, lil, lil); 
      fill(sdblue4); 
     rect ( lilboxsp * 32 , maintoph + lilboxsp * 9, lil, lil); 
     fill(sdblue3); 
     rect ( lilboxsp * 33 , maintoph + lilboxsp * 9, lil, lil); 
     fill(sdblue5); 
     rect ( lilboxsp * 34 , maintoph + lilboxsp * 9, lil, lil); 
      fill(sdblue4); 
     rect ( lilboxsp * 35 , maintoph + lilboxsp * 9, lil, lil); 
     fill(sdblue3); 
     rect ( lilboxsp * 36 , maintoph + lilboxsp * 9, lil, lil); 
     fill(sdblue6); 
     rect ( lilboxsp * 37 , maintoph + lilboxsp * 9, lil, lil); 
     fill(sdblue5); 
     rect ( lilboxsp * 38 , maintoph + lilboxsp * 9, lil, lil); 
      fill(sdblue4); 
     rect ( lilboxsp * 39 , maintoph + lilboxsp * 9, lil, lil); 
     fill(sdblue3); 
     rect ( lilboxsp * 40 , maintoph + lilboxsp * 9, lil, lil); 
     
       fill(sdblue4); 
      rect ( lilboxsp * 41, maintoph + lilboxsp * 9, lil, lil); 
      fill(sdblue3); 
     rect ( lilboxsp * 42 , maintoph + lilboxsp * 9, lil, lil); 
     fill(sdblue6); 
     rect ( lilboxsp * 43 , maintoph + lilboxsp * 9, lil, lil); 
     fill(sdblue6); 
     rect ( lilboxsp * 44 , maintoph + lilboxsp * 9, lil, lil); 
      fill(sdblue3); 
     rect ( lilboxsp * 45 , maintoph + lilboxsp * 9, lil, lil); 
     fill(sdblue5); 
     rect ( lilboxsp * 46 , maintoph + lilboxsp * 9, lil, lil); 
     fill(sdblue6); 
     rect ( lilboxsp * 47 , maintoph + lilboxsp * 9, lil, lil); 
     fill(sdblue3); 
     rect ( lilboxsp * 48 , maintoph + lilboxsp * 9, lil, lil); 
      fill(sdblue4); 
     rect ( lilboxsp * 49 , maintoph + lilboxsp * 9, lil, lil); 
     fill(sdblue6); 
     rect ( lilboxsp * 50 , maintoph + lilboxsp * 9, lil, lil);  
     fill(sdblue3); 
      rect ( lilboxsp * 51, maintoph + lilboxsp * 9, lil, lil); 
      fill(sdblue5); 
     rect ( lilboxsp * 52 , maintoph + lilboxsp * 9, lil, lil); 
     fill(sdblue4); 
     rect ( lilboxsp * 53 , maintoph + lilboxsp * 9, lil, lil); 
     fill(sdblue5); 
     rect ( lilboxsp * 54 , maintoph + lilboxsp * 9, lil, lil); 
      fill(sdblue3); 
     rect ( lilboxsp * 55 , maintoph + lilboxsp * 9, lil, lil);
//10thline
     fill(sdblue3); 
     rect ( 0, maintoph + lilboxsp * 10 , lil, lil); 
      fill(sdblue5); 
     rect ( lilboxsp , maintoph  + lilboxsp * 10, lil, lil); 
      fill(sdblue4); 
     rect ( lilboxsp * 2 , maintoph  + lilboxsp * 10, lil, lil); 
     fill(sdblue6); 
     rect ( lilboxsp * 3 , maintoph + lilboxsp * 10, lil, lil); 
     fill(sdblue5); 
     rect ( lilboxsp * 4 , maintoph + lilboxsp * 10, lil, lil); 
      fill(sdblue4); 
     rect ( lilboxsp * 5 , maintoph + lilboxsp * 10, lil, lil); 
     fill(sdblue6); 
     rect ( lilboxsp * 6 , maintoph + lilboxsp * 10, lil, lil); 
     fill(sdblue5); 
     rect ( lilboxsp * 7 , maintoph + lilboxsp * 10, lil, lil); 
     fill(sdblue3); 
     rect ( lilboxsp * 8 , maintoph + lilboxsp * 10, lil, lil); 
      fill(sdblue5); 
     rect ( lilboxsp * 9 , maintoph + lilboxsp * 10, lil, lil); 
     fill(sdblue6); 
     rect ( lilboxsp * 10 , maintoph + lilboxsp * 10, lil, lil); 
      fill(sdblue3); 
      rect ( lilboxsp * 11, maintoph + lilboxsp * 10, lil, lil); 
      fill(sdblue6); 
     rect ( lilboxsp * 12 , maintoph + lilboxsp * 10, lil, lil); 
     fill(sdblue4); 
     rect ( lilboxsp * 13 , maintoph + lilboxsp * 10, lil, lil); 
     fill(sdblue3); 
     rect ( lilboxsp * 14 , maintoph + lilboxsp * 10, lil, lil); 
      fill(sdblue4); 
     rect ( lilboxsp * 15 , maintoph + lilboxsp * 10, lil, lil); 
     fill(sdblue5); 
     rect ( lilboxsp * 16 , maintoph + lilboxsp * 10, lil, lil); 
     fill(sdblue6); 
     rect ( lilboxsp * 17 , maintoph + lilboxsp * 10, lil, lil); 
     fill(sdblue5); 
     rect ( lilboxsp * 18 , maintoph + lilboxsp * 10, lil, lil); 
      fill(sdblue4); 
     rect ( lilboxsp * 19 , maintoph + lilboxsp * 10 , lil, lil); 
     fill(sdblue6); 
     rect ( lilboxsp * 20 , maintoph + lilboxsp * 10, lil, lil); 
     fill(sdblue4); 
    
           fill(sdblue5); 
      rect ( lilboxsp * 21, maintoph + lilboxsp * 10, lil, lil); 
      fill(sdblue3); 
     rect ( lilboxsp * 22 , maintoph + lilboxsp * 10, lil, lil); 
     fill(sdblue4); 
     rect ( lilboxsp * 23 , maintoph + lilboxsp * 10, lil, lil); 
     fill(sdblue5); 
     rect ( lilboxsp * 24 , maintoph + lilboxsp * 10, lil, lil); 
      fill(sdblue4); 
     rect ( lilboxsp * 25 , maintoph + lilboxsp * 10, lil, lil); 
     fill(sdblue6); 
     rect ( lilboxsp * 26 , maintoph + lilboxsp * 10, lil, lil); 
     fill(sdblue4); 
     rect ( lilboxsp * 27 , maintoph + lilboxsp * 10, lil, lil); 
     fill(sdblue3); 
     rect ( lilboxsp * 28 , maintoph + lilboxsp * 10, lil, lil); 
      fill(sdblue5); 
     rect ( lilboxsp * 29 , maintoph + lilboxsp * 10, lil, lil); 
     fill(sdblue3); 
     rect ( lilboxsp * 30 , maintoph + lilboxsp * 10, lil, lil); 
     
       fill(sdblue5); 
      rect ( lilboxsp * 31, maintoph + lilboxsp * 10, lil, lil); 
      fill(sdblue4); 
     rect ( lilboxsp * 32 , maintoph + lilboxsp * 10, lil, lil); 
     fill(sdblue3); 
     rect ( lilboxsp * 33 , maintoph + lilboxsp * 10, lil, lil); 
     fill(sdblue5); 
     rect ( lilboxsp * 34 , maintoph + lilboxsp * 10, lil, lil); 
      fill(sdblue4); 
     rect ( lilboxsp * 35 , maintoph + lilboxsp * 10, lil, lil); 
     fill(sdblue3); 
     rect ( lilboxsp * 36 , maintoph + lilboxsp * 10, lil, lil); 
     fill(sdblue6); 
     rect ( lilboxsp * 37 , maintoph + lilboxsp * 10, lil, lil); 
     fill(sdblue5); 
     rect ( lilboxsp * 38 , maintoph + lilboxsp * 10, lil, lil); 
      fill(sdblue4); 
     rect ( lilboxsp * 39 , maintoph + lilboxsp * 10, lil, lil); 
     fill(sdblue3); 
     rect ( lilboxsp * 40 , maintoph + lilboxsp * 10, lil, lil); 
     
       fill(sdblue4); 
      rect ( lilboxsp * 41, maintoph + lilboxsp * 10, lil, lil); 
      fill(sdblue3); 
     rect ( lilboxsp * 42 , maintoph + lilboxsp * 10, lil, lil); 
     fill(sdblue6); 
     rect ( lilboxsp * 43 , maintoph + lilboxsp * 10, lil, lil); 
     fill(sdblue6); 
     rect ( lilboxsp * 44 , maintoph + lilboxsp * 10, lil, lil); 
      fill(sdblue3); 
     rect ( lilboxsp * 45 , maintoph + lilboxsp * 10, lil, lil); 
     fill(sdblue5); 
     rect ( lilboxsp * 46 , maintoph + lilboxsp * 10, lil, lil); 
     fill(sdblue6); 
     rect ( lilboxsp * 47 , maintoph + lilboxsp * 10, lil, lil); 
     fill(sdblue3); 
     rect ( lilboxsp * 48 , maintoph + lilboxsp * 10, lil, lil); 
      fill(sdblue4); 
     rect ( lilboxsp * 49 , maintoph + lilboxsp * 10, lil, lil); 
     fill(sdblue6); 
     rect ( lilboxsp * 50 , maintoph + lilboxsp * 10, lil, lil);  
     fill(sdblue3); 
      rect ( lilboxsp * 51, maintoph + lilboxsp * 10, lil, lil); 
      fill(sdblue5); 
     rect ( lilboxsp * 52 , maintoph + lilboxsp * 10, lil, lil); 
     fill(sdblue4); 
     rect ( lilboxsp * 53 , maintoph + lilboxsp * 10, lil, lil); 
     fill(sdblue5); 
     rect ( lilboxsp * 54 , maintoph + lilboxsp * 10, lil, lil); 
      fill(sdblue3); 
     rect ( lilboxsp * 55 , maintoph + lilboxsp * 10, lil, lil);
//11thline
     fill(sdblue3); 
     rect ( 0, maintoph + lilboxsp * 11 , lil, lil); 
      fill(sdblue5); 
     rect ( lilboxsp , maintoph  + lilboxsp * 11, lil, lil); 
      fill(sdblue4); 
     rect ( lilboxsp * 2 , maintoph  + lilboxsp * 11, lil, lil); 
     fill(sdblue6); 
     rect ( lilboxsp * 3 , maintoph + lilboxsp * 11, lil, lil); 
     fill(sdblue5); 
     rect ( lilboxsp * 4 , maintoph + lilboxsp * 11, lil, lil); 
      fill(sdblue4); 
     rect ( lilboxsp * 5 , maintoph + lilboxsp * 11, lil, lil); 
     fill(sdblue6); 
     rect ( lilboxsp * 6 , maintoph + lilboxsp * 11, lil, lil); 
     fill(sdblue5); 
     rect ( lilboxsp * 7 , maintoph + lilboxsp * 11, lil, lil); 
     fill(sdblue3); 
     rect ( lilboxsp * 8 , maintoph + lilboxsp * 11, lil, lil); 
      fill(sdblue5); 
     rect ( lilboxsp * 9 , maintoph + lilboxsp * 11, lil, lil); 
     fill(sdblue6); 
     rect ( lilboxsp * 10 , maintoph + lilboxsp * 11, lil, lil); 
      fill(sdblue3); 
      rect ( lilboxsp * 11, maintoph + lilboxsp * 11, lil, lil); 
      fill(sdblue6); 
     rect ( lilboxsp * 12 , maintoph + lilboxsp * 11, lil, lil); 
     fill(sdblue4); 
     rect ( lilboxsp * 13 , maintoph + lilboxsp * 11, lil, lil); 
     fill(sdblue3); 
     rect ( lilboxsp * 14 , maintoph + lilboxsp * 11, lil, lil); 
      fill(sdblue4); 
     rect ( lilboxsp * 15 , maintoph + lilboxsp * 11, lil, lil); 
     fill(sdblue5); 
     rect ( lilboxsp * 16 , maintoph + lilboxsp * 11, lil, lil); 
     fill(sdblue6); 
     rect ( lilboxsp * 17 , maintoph + lilboxsp * 11, lil, lil); 
     fill(sdblue5); 
     rect ( lilboxsp * 18 , maintoph + lilboxsp * 11, lil, lil); 
      fill(sdblue4); 
     rect ( lilboxsp * 19 , maintoph + lilboxsp * 11 , lil, lil); 
     fill(sdblue6); 
     rect ( lilboxsp * 20 , maintoph + lilboxsp * 11, lil, lil); 
     fill(sdblue4); 
    
           fill(sdblue5); 
      rect ( lilboxsp * 21, maintoph + lilboxsp * 11, lil, lil); 
      fill(sdblue3); 
     rect ( lilboxsp * 22 , maintoph + lilboxsp * 11, lil, lil); 
     fill(sdblue4); 
     rect ( lilboxsp * 23 , maintoph + lilboxsp * 11, lil, lil); 
     fill(sdblue5); 
     rect ( lilboxsp * 24 , maintoph + lilboxsp * 11, lil, lil); 
      fill(sdblue4); 
     rect ( lilboxsp * 25 , maintoph + lilboxsp * 11, lil, lil); 
     fill(sdblue6); 
     rect ( lilboxsp * 26 , maintoph + lilboxsp * 11, lil, lil); 
     fill(sdblue4); 
     rect ( lilboxsp * 27 , maintoph + lilboxsp * 11, lil, lil); 
     fill(sdblue3); 
     rect ( lilboxsp * 28 , maintoph + lilboxsp * 11, lil, lil); 
      fill(sdblue5); 
     rect ( lilboxsp * 29 , maintoph + lilboxsp * 11, lil, lil); 
     fill(sdblue3); 
     rect ( lilboxsp * 30 , maintoph + lilboxsp * 11, lil, lil); 
     
       fill(sdblue5); 
      rect ( lilboxsp * 31, maintoph + lilboxsp * 11, lil, lil); 
      fill(sdblue4); 
     rect ( lilboxsp * 32 , maintoph + lilboxsp * 11, lil, lil); 
     fill(sdblue3); 
     rect ( lilboxsp * 33 , maintoph + lilboxsp * 11, lil, lil); 
     fill(sdblue5); 
     rect ( lilboxsp * 34 , maintoph + lilboxsp * 11, lil, lil); 
      fill(sdblue4); 
     rect ( lilboxsp * 35 , maintoph + lilboxsp * 11, lil, lil); 
     fill(sdblue3); 
     rect ( lilboxsp * 36 , maintoph + lilboxsp * 11, lil, lil); 
     fill(sdblue6); 
     rect ( lilboxsp * 37 , maintoph + lilboxsp * 11, lil, lil); 
     fill(sdblue5); 
     rect ( lilboxsp * 38 , maintoph + lilboxsp * 11, lil, lil); 
      fill(sdblue4); 
     rect ( lilboxsp * 39 , maintoph + lilboxsp * 11, lil, lil); 
     fill(sdblue3); 
     rect ( lilboxsp * 40 , maintoph + lilboxsp * 11, lil, lil); 
     
       fill(sdblue4); 
      rect ( lilboxsp * 41, maintoph + lilboxsp * 11, lil, lil); 
      fill(sdblue3); 
     rect ( lilboxsp * 42 , maintoph + lilboxsp * 11, lil, lil); 
     fill(sdblue6); 
     rect ( lilboxsp * 43 , maintoph + lilboxsp * 11, lil, lil); 
     fill(sdblue6); 
     rect ( lilboxsp * 44 , maintoph + lilboxsp * 11, lil, lil); 
      fill(sdblue3); 
     rect ( lilboxsp * 45 , maintoph + lilboxsp * 11, lil, lil); 
     fill(sdblue5); 
     rect ( lilboxsp * 46 , maintoph + lilboxsp * 11, lil, lil); 
     fill(sdblue6); 
     rect ( lilboxsp * 47 , maintoph + lilboxsp * 11, lil, lil); 
     fill(sdblue3); 
     rect ( lilboxsp * 48 , maintoph + lilboxsp * 11, lil, lil); 
      fill(sdblue4); 
     rect ( lilboxsp * 49 , maintoph + lilboxsp * 11, lil, lil); 
     fill(sdblue6); 
     rect ( lilboxsp * 50 , maintoph + lilboxsp * 11, lil, lil);  
     fill(sdblue3); 
      rect ( lilboxsp * 51, maintoph + lilboxsp * 11, lil, lil); 
      fill(sdblue5); 
     rect ( lilboxsp * 52 , maintoph + lilboxsp * 11, lil, lil); 
     fill(sdblue4); 
     rect ( lilboxsp * 53 , maintoph + lilboxsp * 11, lil, lil); 
     fill(sdblue5); 
     rect ( lilboxsp * 54 , maintoph + lilboxsp * 11, lil, lil); 
      fill(sdblue3); 
     rect ( lilboxsp * 55 , maintoph + lilboxsp * 11, lil, lil);
//12thliine
     fill(sdblue3); 
     rect ( 0, maintoph + lilboxsp * 12 , lil, lil); 
      fill(sdblue5); 
     rect ( lilboxsp , maintoph  + lilboxsp * 12, lil, lil); 
      fill(sdblue4); 
     rect ( lilboxsp * 2 , maintoph  + lilboxsp * 12, lil, lil); 
     fill(sdblue6); 
     rect ( lilboxsp * 3 , maintoph + lilboxsp * 12, lil, lil); 
     fill(sdblue5); 
     rect ( lilboxsp * 4 , maintoph + lilboxsp * 12, lil, lil); 
      fill(sdblue4); 
     rect ( lilboxsp * 5 , maintoph + lilboxsp * 12, lil, lil); 
     fill(sdblue6); 
     rect ( lilboxsp * 6 , maintoph + lilboxsp * 12, lil, lil); 
     fill(sdblue5); 
     rect ( lilboxsp * 7 , maintoph + lilboxsp * 12, lil, lil); 
     fill(sdblue3); 
     rect ( lilboxsp * 8 , maintoph + lilboxsp * 12, lil, lil); 
      fill(sdblue5); 
     rect ( lilboxsp * 9 , maintoph + lilboxsp * 12, lil, lil); 
     fill(sdblue6); 
     rect ( lilboxsp * 10 , maintoph + lilboxsp * 12, lil, lil); 
      fill(sdblue3); 
      rect ( lilboxsp * 11, maintoph + lilboxsp * 12, lil, lil); 
      fill(sdblue6); 
     rect ( lilboxsp * 12 , maintoph + lilboxsp * 12, lil, lil); 
     fill(sdblue4); 
     rect ( lilboxsp * 13 , maintoph + lilboxsp * 12, lil, lil); 
     fill(sdblue3); 
     rect ( lilboxsp * 14 , maintoph + lilboxsp * 12, lil, lil); 
      fill(sdblue4); 
     rect ( lilboxsp * 15 , maintoph + lilboxsp * 12, lil, lil); 
     fill(sdblue5); 
     rect ( lilboxsp * 16 , maintoph + lilboxsp * 12, lil, lil); 
     fill(sdblue6); 
     rect ( lilboxsp * 17 , maintoph + lilboxsp * 12, lil, lil); 
     fill(sdblue5); 
     rect ( lilboxsp * 18 , maintoph + lilboxsp * 12, lil, lil); 
      fill(sdblue4); 
     rect ( lilboxsp * 19 , maintoph + lilboxsp * 12 , lil, lil); 
     fill(sdblue6); 
     rect ( lilboxsp * 20 , maintoph + lilboxsp * 12, lil, lil); 
     fill(sdblue4); 
    
           fill(sdblue5); 
      rect ( lilboxsp * 21, maintoph + lilboxsp * 12, lil, lil); 
      fill(sdblue3); 
     rect ( lilboxsp * 22 , maintoph + lilboxsp * 12, lil, lil); 
     fill(sdblue4); 
     rect ( lilboxsp * 23 , maintoph + lilboxsp * 12, lil, lil); 
     fill(sdblue5); 
     rect ( lilboxsp * 24 , maintoph + lilboxsp * 12, lil, lil); 
      fill(sdblue4); 
     rect ( lilboxsp * 25 , maintoph + lilboxsp * 12, lil, lil); 
     fill(sdblue6); 
     rect ( lilboxsp * 26 , maintoph + lilboxsp * 12, lil, lil); 
     fill(sdblue4); 
     rect ( lilboxsp * 27 , maintoph + lilboxsp * 12, lil, lil); 
     fill(sdblue3); 
     rect ( lilboxsp * 28 , maintoph + lilboxsp * 12, lil, lil); 
      fill(sdblue5); 
     rect ( lilboxsp * 29 , maintoph + lilboxsp * 12, lil, lil); 
     fill(sdblue3); 
     rect ( lilboxsp * 30 , maintoph + lilboxsp * 12, lil, lil); 
     
       fill(sdblue5); 
      rect ( lilboxsp * 31, maintoph + lilboxsp * 12, lil, lil); 
      fill(sdblue4); 
     rect ( lilboxsp * 32 , maintoph + lilboxsp * 12, lil, lil); 
     fill(sdblue3); 
     rect ( lilboxsp * 33 , maintoph + lilboxsp * 12, lil, lil); 
     fill(sdblue5); 
     rect ( lilboxsp * 34 , maintoph + lilboxsp * 12, lil, lil); 
      fill(sdblue4); 
     rect ( lilboxsp * 35 , maintoph + lilboxsp * 12, lil, lil); 
     fill(sdblue3); 
     rect ( lilboxsp * 36 , maintoph + lilboxsp * 12, lil, lil); 
     fill(sdblue6); 
     rect ( lilboxsp * 37 , maintoph + lilboxsp * 12, lil, lil); 
     fill(sdblue5); 
     rect ( lilboxsp * 38 , maintoph + lilboxsp * 12, lil, lil); 
      fill(sdblue4); 
     rect ( lilboxsp * 39 , maintoph + lilboxsp * 12, lil, lil); 
     fill(sdblue3); 
     rect ( lilboxsp * 40 , maintoph + lilboxsp * 12, lil, lil); 
     
       fill(sdblue4); 
      rect ( lilboxsp * 41, maintoph + lilboxsp * 12, lil, lil); 
      fill(sdblue3); 
     rect ( lilboxsp * 42 , maintoph + lilboxsp * 12, lil, lil); 
     fill(sdblue6); 
     rect ( lilboxsp * 43 , maintoph + lilboxsp * 12, lil, lil); 
     fill(sdblue6); 
     rect ( lilboxsp * 44 , maintoph + lilboxsp * 12, lil, lil); 
      fill(sdblue3); 
     rect ( lilboxsp * 45 , maintoph + lilboxsp * 12, lil, lil); 
     fill(sdblue5); 
     rect ( lilboxsp * 46 , maintoph + lilboxsp * 12, lil, lil); 
     fill(sdblue6); 
     rect ( lilboxsp * 47 , maintoph + lilboxsp * 12, lil, lil); 
     fill(sdblue3); 
     rect ( lilboxsp * 48 , maintoph + lilboxsp * 12, lil, lil); 
      fill(sdblue4); 
     rect ( lilboxsp * 49 , maintoph + lilboxsp * 12, lil, lil); 
     fill(sdblue6); 
     rect ( lilboxsp * 50 , maintoph + lilboxsp * 12, lil, lil);  
     fill(sdblue3); 
      rect ( lilboxsp * 51, maintoph + lilboxsp * 12, lil, lil); 
      fill(sdblue5); 
     rect ( lilboxsp * 52 , maintoph + lilboxsp * 12, lil, lil); 
     fill(sdblue4); 
     rect ( lilboxsp * 53 , maintoph + lilboxsp * 12, lil, lil); 
     fill(sdblue5); 
     rect ( lilboxsp * 54 , maintoph + lilboxsp * 12, lil, lil); 
      fill(sdblue3); 
     rect ( lilboxsp * 55 , maintoph + lilboxsp * 12, lil, lil);
//13.th line
     fill(sdblue3); 
     rect ( 0, maintoph + lilboxsp * 13 , lil, lil); 
      fill(sdblue5); 
     rect ( lilboxsp , maintoph  + lilboxsp * 13, lil, lil); 
      fill(sdblue4); 
     rect ( lilboxsp * 2 , maintoph  + lilboxsp * 13, lil, lil); 
     fill(sdblue6); 
     rect ( lilboxsp * 3 , maintoph + lilboxsp * 13, lil, lil); 
     fill(sdblue5); 
     rect ( lilboxsp * 4 , maintoph + lilboxsp * 13, lil, lil); 
      fill(sdblue4); 
     rect ( lilboxsp * 5 , maintoph + lilboxsp * 13, lil, lil); 
     fill(sdblue6); 
     rect ( lilboxsp * 6 , maintoph + lilboxsp * 13, lil, lil); 
     fill(sdblue5); 
     rect ( lilboxsp * 7 , maintoph + lilboxsp * 13, lil, lil); 
     fill(sdblue3); 
     rect ( lilboxsp * 8 , maintoph + lilboxsp * 13, lil, lil); 
      fill(sdblue5); 
     rect ( lilboxsp * 9 , maintoph + lilboxsp * 13, lil, lil); 
     fill(sdblue6); 
     rect ( lilboxsp * 10 , maintoph + lilboxsp * 13, lil, lil); 
      fill(sdblue3); 
      rect ( lilboxsp * 11, maintoph + lilboxsp * 13, lil, lil); 
      fill(sdblue6); 
     rect ( lilboxsp * 12, maintoph + lilboxsp * 13, lil, lil); 
     fill(sdblue4); 
     rect ( lilboxsp * 13 , maintoph + lilboxsp * 13, lil, lil); 
     fill(sdblue3); 
     rect ( lilboxsp * 14 , maintoph + lilboxsp * 13, lil, lil); 
      fill(sdblue4); 
     rect ( lilboxsp * 15 , maintoph + lilboxsp * 13, lil, lil); 
     fill(sdblue5); 
     rect ( lilboxsp * 16 , maintoph + lilboxsp * 13, lil, lil); 
     fill(sdblue6); 
     rect ( lilboxsp * 17 , maintoph + lilboxsp * 13, lil, lil); 
     fill(sdblue5); 
     rect ( lilboxsp * 18 , maintoph + lilboxsp * 13, lil, lil); 
      fill(sdblue4); 
     rect ( lilboxsp * 19 , maintoph + lilboxsp * 13 , lil, lil); 
     fill(sdblue6); 
     rect ( lilboxsp * 20 , maintoph + lilboxsp * 13, lil, lil); 
     fill(sdblue4); 
    
           fill(sdblue5); 
      rect ( lilboxsp * 21, maintoph + lilboxsp * 13, lil, lil); 
      fill(sdblue3); 
     rect ( lilboxsp * 22 , maintoph + lilboxsp * 13, lil, lil); 
     fill(sdblue4); 
     rect ( lilboxsp * 23 , maintoph + lilboxsp * 13, lil, lil); 
     fill(sdblue5); 
     rect ( lilboxsp * 24 , maintoph + lilboxsp * 13, lil, lil); 
      fill(sdblue4); 
     rect ( lilboxsp * 25 , maintoph + lilboxsp * 13, lil, lil); 
     fill(sdblue6); 
     rect ( lilboxsp * 26 , maintoph + lilboxsp * 13, lil, lil); 
     fill(sdblue4); 
     rect ( lilboxsp * 27 , maintoph + lilboxsp * 13, lil, lil); 
     fill(sdblue3); 
     rect ( lilboxsp * 28 , maintoph + lilboxsp * 13, lil, lil); 
      fill(sdblue5); 
     rect ( lilboxsp * 29 , maintoph + lilboxsp * 13, lil, lil); 
     fill(sdblue3); 
     rect ( lilboxsp * 30 , maintoph + lilboxsp * 13, lil, lil); 
     
       fill(sdblue5); 
      rect ( lilboxsp * 31, maintoph + lilboxsp * 13, lil, lil); 
      fill(sdblue4); 
     rect ( lilboxsp * 32 , maintoph + lilboxsp * 13, lil, lil); 
     fill(sdblue3); 
     rect ( lilboxsp * 33 , maintoph + lilboxsp * 13, lil, lil); 
     fill(sdblue5); 
     rect ( lilboxsp * 34 , maintoph + lilboxsp * 13, lil, lil); 
      fill(sdblue4); 
     rect ( lilboxsp * 35 , maintoph + lilboxsp * 13, lil, lil); 
     fill(sdblue3); 
     rect ( lilboxsp * 36 , maintoph + lilboxsp * 13, lil, lil); 
     fill(sdblue6); 
     rect ( lilboxsp * 37 , maintoph + lilboxsp * 13, lil, lil); 
     fill(sdblue5); 
     rect ( lilboxsp * 38 , maintoph + lilboxsp * 13, lil, lil); 
      fill(sdblue4); 
     rect ( lilboxsp * 39 , maintoph + lilboxsp * 13, lil, lil); 
     fill(sdblue3); 
     rect ( lilboxsp * 40 , maintoph + lilboxsp * 13, lil, lil); 
     
       fill(sdblue4); 
      rect ( lilboxsp * 41, maintoph + lilboxsp * 13, lil, lil); 
      fill(sdblue3); 
     rect ( lilboxsp * 42 , maintoph + lilboxsp * 13, lil, lil); 
     fill(sdblue6); 
     rect ( lilboxsp * 43 , maintoph + lilboxsp * 13, lil, lil); 
     fill(sdblue6); 
     rect ( lilboxsp * 44 , maintoph + lilboxsp * 13, lil, lil); 
      fill(sdblue3); 
     rect ( lilboxsp * 45 , maintoph + lilboxsp * 13, lil, lil); 
     fill(sdblue5); 
     rect ( lilboxsp * 46 , maintoph + lilboxsp * 13, lil, lil); 
     fill(sdblue6); 
     rect ( lilboxsp * 47 , maintoph + lilboxsp * 13, lil, lil); 
     fill(sdblue3); 
     rect ( lilboxsp * 48 , maintoph + lilboxsp * 13, lil, lil); 
      fill(sdblue4); 
     rect ( lilboxsp * 49 , maintoph + lilboxsp * 13, lil, lil); 
     fill(sdblue6); 
     rect ( lilboxsp * 50 , maintoph + lilboxsp * 13, lil, lil);  
     fill(sdblue3); 
      rect ( lilboxsp * 51, maintoph + lilboxsp * 13, lil, lil); 
      fill(sdblue5); 
     rect ( lilboxsp * 52 , maintoph + lilboxsp * 13, lil, lil); 
     fill(sdblue4); 
     rect ( lilboxsp * 53 , maintoph + lilboxsp * 13, lil, lil); 
     fill(sdblue5); 
     rect ( lilboxsp * 54 , maintoph + lilboxsp * 13, lil, lil); 
      fill(sdblue3); 
     rect ( lilboxsp * 55 , maintoph + lilboxsp * 13, lil, lil);

fill(255);
ellipse(mainh / 2 , maintoph + 60 , ch , cw);
ellipse(mainh  / 2 ,  maintoph + 219 , ch , cw)
;ellipse(mainh / 2  - 90, maintoph + 140 , cw , ch);
ellipse(mainh / 2  + ch / 2, maintoph + 140 , cw , ch);
 }
